#include <Arduino.h>
#include <ArduinoYaml.h>
#include <homie/homie.h>
#include <homie/Device.h>
#include <platform/config.h>
#include <platform/mqtt_client.h>
#include <util/jsonUtils.h>
/*
  homie/5/device123/$state → ready
  homie/5/device123/$description → {
    "id": "device123",
    "homie": "5.0",
    "version": "12",
    "name": "My device",
    "nodes": {
      "mythermostat": {
        "name": "My thermostat",
        "type": "thermostat",
        "properties": {
          "temperature": {
            "name": "Temperature",
            "unit": "°C",
            "datatype": "integer",
            "settable": true
          }
        }
      }
    }
  }
*/
Device::Device() {
    _num_nodes = 0;
    _state = DeviceState::DEVICE_STATE_INIT;
}

void Device::addNodePropertiesFromConfigJson(Node* n, JsonVariant node_json, bool subscribe) {
    JsonVariant props = node_json[HOMIE_PROPERTIES].as<JsonArray>();
    for(JsonVariant json_prop : props.as<JsonArray>()) {
      if (json_prop.is<JsonObject>()) {
        Property* prop = new Property();
        prop->setNode(n); // required: set the parent node on the property before anything else
        prop->setMQTTClient(_mqtt_client);
        JsonObject props_obj = json_prop.as<JsonObject>();
        prop->from_dict(&props_obj); // Initialize property from JsonObject
        n->addProperty(prop);
        if (subscribe && prop->settable()) {
          prop->subscribe();
        }
      }
    }
}

void Device::init(const char* name, const char* id, const char* type, MQTTClient* mqtt_client) {
  setName(name);
  setId(id);
  setType(type);
  _mqtt_client = mqtt_client;
  // Topic uses device ID (e.g. homie/5/ESP32POEISO_A1B2C3/)
  snprintf(_topic, sizeof(_topic), "%s/%s/", HOMIE_TOPIC_PREFIX, id);
  // Nodes and properties are registered by register_homie_properties() — generated by ebus-esp32
}

Node* Device::addNode(const char* id, const char* name, const char* type) {
    if (_num_nodes >= MAX_NODES) {
        Serial.printf("Device: ERROR node limit (%d) reached — '%s' NOT added\n", MAX_NODES, id);
        return nullptr;
    }
    Node* n = new Node();
    n->setDevice(this);
    n->setId(id);
    n->setName(name);
    n->setType(type);
    n->setTopic(_topic);
    n->setMQTTClient(_mqtt_client);
    Serial.printf("Device: Node: Adding '%s' id '%s'\n", name, id);
    _nodes[_num_nodes++] = n;
    return n;
}

Node* Device::addNode(JsonVariant node, const char* topic) {
    if (_num_nodes >= MAX_NODES) {
        Serial.printf("Device: ERROR node limit (%d) reached — node NOT added\n", MAX_NODES);
        return nullptr;
    }
    Node* n =  new Node();
    n->setDevice(this);
    if (jsonExists(node[HOMIE_ID])) n->setId(node[HOMIE_ID].as<const char*>());
    if (jsonExists(node[HOMIE_NAME])) n->setName(node[HOMIE_NAME].as<const char*>());
    if (jsonExists(node[HOMIE_TYPE])) n->setType(node[HOMIE_TYPE].as<const char*>());
    n->setTopic(topic);
    Serial.printf("Device: Node: Adding '%s' with id '%s'\n", n->name(), n->id());
    _nodes[_num_nodes++] = n;
    return n;
}

Node* Device::getNode(const char* id) {
  for (int i = 0; i < _num_nodes; i++) {
      if (strcmp(_nodes[i]->id(), id) == 0) {
          return _nodes[i];
      }
  }
  Serial.printf("Device: Node '%s' not found\n", id);
  return nullptr;
}

// --- Nested-device tree (Homie 5 parent/child) ---

void Device::addChild(Device* child) {
  if (!child) return;
  child->_parent = this;
  child->_next_sibling = nullptr;
  // Append to the sibling list so children keep insertion order.
  if (!_first_child) {
    _first_child = child;
  } else {
    Device* s = _first_child;
    while (s->_next_sibling) s = s->_next_sibling;
    s->_next_sibling = child;
  }
  _num_children++;
  Serial.printf("Device '%s': added child '%s'\n", _id, child->getId());
}

Device* Device::root() {
  Device* d = this;
  while (d->_parent) d = d->_parent;
  return d;
}

const char* Device::parentId() {
  return _parent ? _parent->getId() : nullptr;
}

const char* Device::rootId() {
  return _parent ? root()->getId() : nullptr;
}

// Publish this device and every descendant: each emits its own $state +
// $description + node values over the shared (root) MQTT connection. Depth-first,
// parents before children. (The ordered Homie add-child INIT/READY protocol is
// A6; this is the straight whole-tree publish.)
void Device::publishTree() {
  publishState();
  publish();
  for (Device* c = _first_child; c; c = c->_next_sibling) {
    c->publishTree();
  }
}

// Republish $state for this device and every descendant. Used on MQTT reconnect:
// the broker's Last Will set the ROOT's $state to "lost" (which, per Homie 5,
// cascades the lost state to the whole tree), so on reconnect every device must
// re-assert its own $state to clear the cascade.
void Device::publishStateTree() {
  publishState();
  for (Device* c = _first_child; c; c = c->_next_sibling) {
    c->publishStateTree();
  }
}

// Runtime add following the Homie 5 ordered protocol (convention §"Adding children"):
// publish the child fully (init -> $description -> ready), THEN cycle the parent
// (init -> updated $description listing the child -> ready). Cycling through init is
// what lets the parent's $description change (it may only change in init/disc/lost).
void Device::addChildLive(Device* child) {
  if (!child) return;
  addChild(child);                       // link first: the child can now resolve root/parent
  // 1. publish the child
  child->setState(DEVICE_STATE_INIT);
  child->publishState();                 // emit init explicitly (setState no-ops if already init)
  child->publish();                      // $description (with root/parent) + nodes
  child->setState(DEVICE_STATE_READY);
  // 2. update the parent
  setState(DEVICE_STATE_INIT);
  publish();                             // parent $description now lists the child
  setState(DEVICE_STATE_READY);
}

// Runtime remove (convention §"Removing children"): cycle the parent (init ->
// $description without the child -> ready), THEN clear the child's retained topics
// starting with $state (an empty $state means the device ceases to exist).
void Device::removeChildLive(Device* child) {
  if (!child) return;
  // 1. update the parent
  setState(DEVICE_STATE_INIT);
  unlinkChild(child);                    // so serialize() omits the child
  publish();
  setState(DEVICE_STATE_READY);
  // 2. clear the child's retained topics
  child->clearRetained();
  child->_parent = nullptr;
}

void Device::unlinkChild(Device* child) {
  if (_first_child == child) {
    _first_child = child->_next_sibling;
  } else {
    for (Device* s = _first_child; s; s = s->_next_sibling) {
      if (s->_next_sibling == child) { s->_next_sibling = child->_next_sibling; break; }
    }
  }
  child->_next_sibling = nullptr;
  if (_num_children > 0) _num_children--;
}

// Publish a zero-length retained payload to this device's $state, $description, and
// each property topic — removing the retained messages. $state first, per the spec.
void Device::clearRetained() {
  if (!_mqtt_client) return;
  char top[160] = {0};
  snprintf(top, sizeof(top), "%s%s", topic(), HOMIE_$STATE);
  _mqtt_client->publish(top, "", true, 0);
  snprintf(top, sizeof(top), "%s%s", topic(), HOMIE_$DESCRIPTION);
  _mqtt_client->publish(top, "", true, 0);
  for (int i = 0; i < _num_nodes; i++) {
    _nodes[i]->clearRetained();
  }
}

void Device::setState(DeviceState state) {
  DeviceState previous_state = _state;
  _state = state;

  //state change?
  if (_state != previous_state) {
    publishState();
  }
}

void Device::setId(const char* id) {
    strncpy(_id, id, sizeof(_id) - 1);
    _id[sizeof(_id) - 1] = '\0';
    //SET-ID SIDE-EFFECT: set topic
    snprintf(_topic, sizeof(_topic), "%s/%s/", HOMIE_TOPIC_PREFIX, _id);
}

void Device::setName(const char* name) {
    snprintf(_name, sizeof(_name), "%s", name);
}

void Device::setType(const char* type) {
    snprintf(_type, sizeof(_type), "%s", type);
}

const char* Device::type() {
    return _type;
}

void Device::setMQTTClient(MQTTClient* client) {
  _mqtt_client = client;
  for(int i=0; i < _num_nodes; i++) {
      _nodes[i]->setMQTTClient(client); // Set the MQTT client for each node
  }
}

void Device::mqttConnected() {
  for(int i=0;i<_num_nodes;i++) {
    _nodes[i]->mqttConnected();
  }
}

const char* Device::topic() {
    return _topic;
}

size_t Device::toJson(char* buffer, size_t bufferSize) {
    return serialize(buffer, bufferSize);
}

char* Device::getId() {
    return _id;
}

// JSON serialization — single document to avoid cross-doc copy issues
size_t Device::serialize(char* buffer, size_t bufferSize) {
  JsonDocument json;
  json[HOMIE_NAME] = _name;
  json[HOMIE_TYPE] = _type;
  // Homie 5 nested-device hierarchy. `children` is always present (empty for a
  // leaf), matching the reference SDK; `root`/`parent` appear only on non-root
  // devices. The tree is referenced by device-id, not embedded.
  JsonArray children = json[HOMIE_CHILDREN].to<JsonArray>();
  for (Device* c = _first_child; c; c = c->_next_sibling) {
    children.add(c->getId());
  }
  if (_parent) {
    json[HOMIE_ROOT]   = root()->getId();
    json[HOMIE_PARENT] = _parent->getId();
  }
  JsonObject nodes_obj = json[HOMIE_NODES].to<JsonObject>();
  for (int i = 0; i < _num_nodes; i++) {
    JsonObject node_obj = nodes_obj[_nodes[i]->id()].to<JsonObject>();
    _nodes[i]->serializeInto(node_obj);
  }
  // Surface silent truncation: serializeJson() caps output at bufferSize-1.
  // Per-device buffer sizing for large/nested trees is tracked in Epic A.
  size_t needed = measureJson(json);
  if (needed + 1 > bufferSize) {
    Serial.printf("Device: ERROR $description needs %u bytes but buffer is %u — TRUNCATED (raise MAX_DATA_LEN)\n",
                  (unsigned)needed, (unsigned)bufferSize);
  }
  return serializeJson(json, buffer, bufferSize);
}

void Device::publishState() {
  char state_topic[128] = {0};
  snprintf(state_topic, sizeof(state_topic), "%s%s", topic(), HOMIE_$STATE);
  const char* state_str = device_state_to_cstr(_state);

  Serial.printf("DEVICE publish: %s -> '%s'\n", state_topic, state_str);

  // MQTTClient publish: (topic, payload, retained, qos)
  if (!_mqtt_client->publish(state_topic, state_str, true, 0)) {
      Serial.println("MQTT publish: $state failed");
  }
}

// Static buffer for $description JSON (avoid stack allocation)
static char _description_json[MAX_DATA_LEN];

void Device::publish() {

  //$description
  Serial.println("DEVICE publish: $description");
  char top[128] = {0};
  snprintf(top, sizeof(top), "%s%s", topic(), HOMIE_$DESCRIPTION);
  size_t len = toJson(_description_json, sizeof(_description_json));
  Serial.printf("DEVICE: $description JSON size: %d bytes\n", len);
  // MQTTClient publish: (topic, payload, retained, qos)
  if (!_mqtt_client->publish(top, _description_json, true, 0)) {
      Serial.println("MQTT publish: $description failed");
  }

  //nodes
  Serial.println("DEVICE publish: nodes");
  for (int i = 0; i < _num_nodes; i++) {
    Serial.printf("DEVICE publish: node: %s\n", _nodes[i]->name());
    _nodes[i]->publish();
  }

}

const char* device_state_to_cstr(DeviceState state) {
    switch (state) {
        case DEVICE_STATE_INIT:         return HOMIE_STATE_INIT;
        case DEVICE_STATE_READY:        return HOMIE_STATE_READY;
        case DEVICE_STATE_DISCONNECTED: return HOMIE_STATE_DISCONNECTED;
        case DEVICE_STATE_SLEEPING:     return HOMIE_STATE_SLEEPING;
        case DEVICE_STATE_LOST:         return HOMIE_STATE_LOST;
        default:                        return HOMIE_STATE_UNKNOWN;
    }
}

// Safe for exact matches only; not case-insensitive
DeviceState device_state_from_cstr(const char* str) {
    if (strcmp(str, "init") == 0)         return DEVICE_STATE_INIT;
    if (strcmp(str, "ready") == 0)        return DEVICE_STATE_READY;
    if (strcmp(str, "disconnected") == 0) return DEVICE_STATE_DISCONNECTED;
    if (strcmp(str, "sleeping") == 0)     return DEVICE_STATE_SLEEPING;
    if (strcmp(str, "lost") == 0)         return DEVICE_STATE_LOST;
    return DEVICE_STATE_UNKNOWN;
}
