#include <Arduino.h>
#include <ArduinoYaml.h>
#include <homie/homie.h>
#include <homie/Device.h>
#include <platform/config.h>
#include <platform/mqtt_client.h>
#include <util/jsonUtils.h>
/*
  homie/5/device123/$state → ready
  homie/5/device123/$description → {
    "id": "device123",
    "homie": "5.0",
    "version": "12",
    "name": "My device",
    "nodes": {
      "mythermostat": {
        "name": "My thermostat",
        "type": "thermostat",
        "properties": {
          "temperature": {
            "name": "Temperature",
            "unit": "°C",
            "datatype": "integer",
            "settable": true
          }
        }
      }
    }
  }
*/
Device::Device() {
    _num_nodes = 0;
    _state = DeviceState::DEVICE_STATE_INIT;
}

void Device::addNodePropertiesFromConfigJson(Node* n, JsonVariant node_json, bool subscribe) {
    JsonVariant props = node_json[HOMIE_PROPERTIES].as<JsonArray>();
    for(JsonVariant json_prop : props.as<JsonArray>()) {
      if (json_prop.is<JsonObject>()) {
        Property* prop = new Property();
        prop->setNode(n); // required: set the parent node on the property before anything else
        prop->setMQTTClient(_mqtt_client);
        JsonObject props_obj = json_prop.as<JsonObject>();
        prop->from_dict(&props_obj); // Initialize property from JsonObject
        n->addProperty(prop);
        if (subscribe && prop->settable()) {
          prop->subscribe();
        }
      }
    }
}

void Device::init(const char* name, const char* id, const char* type, MQTTClient* mqtt_client) {
  setName(name);
  setId(id);
  setType(type);
  _mqtt_client = mqtt_client;
  // Topic uses device ID (e.g. homie/5/ESP32POEISO_A1B2C3/)
  snprintf(_topic, sizeof(_topic), "%s/%s/", HOMIE_TOPIC_PREFIX, id);
  // Nodes and properties are registered by register_homie_properties() — generated by ebus-esp32
}

Node* Device::addNode(const char* id, const char* name, const char* type) {
    Node* n = new Node();
    n->setDevice(this);
    n->setId(id);
    n->setName(name);
    n->setType(type);
    n->setTopic(_topic);
    n->setMQTTClient(_mqtt_client);
    Serial.printf("Device: Node: Adding '%s' id '%s'\n", name, id);
    _nodes[_num_nodes++] = n;
    return n;
}

Node* Device::addNode(JsonVariant node, const char* topic) {
    Node* n =  new Node();
    n->setDevice(this);
    if (jsonExists(node[HOMIE_ID])) n->setId(node[HOMIE_ID].as<const char*>());
    if (jsonExists(node[HOMIE_NAME])) n->setName(node[HOMIE_NAME].as<const char*>());
    if (jsonExists(node[HOMIE_TYPE])) n->setType(node[HOMIE_TYPE].as<const char*>());
    n->setTopic(topic);
    Serial.printf("Device: Node: Adding '%s' with id '%s'\n", n->name(), n->id());
    _nodes[_num_nodes++] = n;
    return n;
}

Node* Device::getNode(const char* id) {
  for (int i = 0; i < _num_nodes; i++) {
      if (strcmp(_nodes[i]->id(), id) == 0) {
          return _nodes[i];
      }
  }
  Serial.printf("Device: Node '%s' not found\n", id);
  return nullptr;
}

void Device::setState(DeviceState state) {
  DeviceState previous_state = _state;
  _state = state;

  //state change?
  if (_state != previous_state) {
    publishState();
  }
}

void Device::setId(const char* id) {
    strncpy(_id, id, sizeof(_id) - 1);
    _id[sizeof(_id) - 1] = '\0';
    //SET-ID SIDE-EFFECT: set topic
    snprintf(_topic, sizeof(_topic), "%s/%s/", HOMIE_TOPIC_PREFIX, _id);
}

void Device::setName(const char* name) {
    strcpy(_name,name);
}

void Device::setType(const char* type) {
    strcpy(_type, type);
}

const char* Device::type() {
    return _type;
}

void Device::setMQTTClient(MQTTClient* client) {
  _mqtt_client = client;
  for(int i=0; i < _num_nodes; i++) {
      _nodes[i]->setMQTTClient(client); // Set the MQTT client for each node
  }
}

void Device::mqttConnected() {
  for(int i=0;i<_num_nodes;i++) {
    _nodes[i]->mqttConnected();
  }
}

const char* Device::topic() {
    return _topic;
}

size_t Device::toJson(char* buffer, size_t bufferSize) {
    return serialize(buffer, bufferSize);
}

char* Device::getId() {
    return _id;
}

// JSON serialization — single document to avoid cross-doc copy issues
size_t Device::serialize(char* buffer, size_t bufferSize) {
  JsonDocument json;
  json[HOMIE_NAME] = _name;
  json[HOMIE_TYPE] = _type;
  JsonObject nodes_obj = json[HOMIE_NODES].to<JsonObject>();
  for (int i = 0; i < _num_nodes; i++) {
    JsonObject node_obj = nodes_obj[_nodes[i]->id()].to<JsonObject>();
    _nodes[i]->serializeInto(node_obj);
  }
  return serializeJson(json, buffer, bufferSize);
}

void Device::publishState() {
  char state_topic[128] = {0};
  sprintf(state_topic, "%s%s", topic(), HOMIE_$STATE);
  const char* state_str = device_state_to_cstr(_state);

  Serial.printf("DEVICE publish: %s -> '%s'\n", state_topic, state_str);

  // MQTTClient publish: (topic, payload, retained, qos)
  if (!_mqtt_client->publish(state_topic, state_str, true, 0)) {
      Serial.println("MQTT publish: $state failed");
  }
}

// Static buffer for $description JSON (avoid stack allocation)
static char _description_json[MAX_DATA_LEN];

void Device::publish() {

  //$description
  Serial.println("DEVICE publish: $description");
  char top[128] = {0};
  sprintf(top, "%s%s", topic(), HOMIE_$DESCRIPTION);
  size_t len = toJson(_description_json, sizeof(_description_json));
  Serial.printf("DEVICE: $description JSON size: %d bytes\n", len);
  // MQTTClient publish: (topic, payload, retained, qos)
  if (!_mqtt_client->publish(top, _description_json, true, 0)) {
      Serial.println("MQTT publish: $description failed");
  }

  //nodes
  Serial.println("DEVICE publish: nodes");
  for (int i = 0; i < _num_nodes; i++) {
    Serial.printf("DEVICE publish: node: %s\n", _nodes[i]->name());
    _nodes[i]->publish();
  }

}

const char* device_state_to_cstr(DeviceState state) {
    switch (state) {
        case DEVICE_STATE_INIT:         return HOMIE_STATE_INIT;
        case DEVICE_STATE_READY:        return HOMIE_STATE_READY;
        case DEVICE_STATE_DISCONNECTED: return HOMIE_STATE_DISCONNECTED;
        case DEVICE_STATE_SLEEPING:     return HOMIE_STATE_SLEEPING;
        case DEVICE_STATE_LOST:         return HOMIE_STATE_LOST;
        default:                        return HOMIE_STATE_UNKNOWN;
    }
}

// Safe for exact matches only; not case-insensitive
DeviceState device_state_from_cstr(const char* str) {
    if (strcmp(str, "init") == 0)         return DEVICE_STATE_INIT;
    if (strcmp(str, "ready") == 0)        return DEVICE_STATE_READY;
    if (strcmp(str, "disconnected") == 0) return DEVICE_STATE_DISCONNECTED;
    if (strcmp(str, "sleeping") == 0)     return DEVICE_STATE_SLEEPING;
    if (strcmp(str, "lost") == 0)         return DEVICE_STATE_LOST;
    return DEVICE_STATE_UNKNOWN;
}
